### ISSUE TITLE
[Nieuwe Idee] Update de database migratie

### ISSUE THREAD

**Issue by nicojs** [nicojs/rock-solid#108]
### Idee

We gaan de meest recente data migreren uit de huidige database. Alvast dingen om op te letten:

- Wat doen we met deelnemers die geen adres meer hebben in de huidige database? (verplaatst naar opmerkingen). Zie https://github.com/nicojs/rock-solid/issues/108#issuecomment-1699801450

**Comment by nicojs** [comment]
We hebben een probleem met de kwaliteit van de deelnemer data. Veel deelnemers hebben nu geen adres, omdat ze geen post meer wilden ontvangen. Dit betekend dat ik voor hun aanmeldingen geen adres kan registeren in rock-solid. Hierdoor kan rock-solid niet aangeven vanuit welke provincie aanmeldingen kwamen. 

Echter hebben we de adressen nog wel, omdat daarvoor vaak het opmerkingen veld werd 'misbruikt'.

Mijn voorstel is dat ik voor het migreren de data van alle deelnemers aanlever aan Rita, dan kan zei de data 1 keer "opschonen" (juiste adressen instellen). 

Overigens mag je in rock-solid de deelnemers die geen post meer willen ontvangen gewoon verwijderen. De deelnames blijven dan bestaan zodat daarover gerapporteerd kan blijven worden (losgekoppeld van de deelnemer).

**Comment by SusDK** [comment]
Lijkt mij inderdaad het beste

**Comment by elimarte** [comment]
Maar dan komen die adressen er terug in, terwijl die mensen verhuisd zijn of geen post meer willen ontvangen.

Kom eens met een beter voorstel, Nico. :)

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________
