### ISSUE TITLE
[Nieuwe Idee] Geboorteplaats?

### ISSUE THREAD

**Issue by nicojs** [nicojs/rock-solid#167]
### Idee

De oude database had ook "geboorteplaats". Is dit ook nuttig voor RockSolid?

**Comment by SusDK** [comment]
Is belangrijk voor vakantiewerking, soms voor Vlaams Opleidingsverlof

**Comment by SusDK** [comment]
Is belangrijk voor vakantiewerking, soms voor Vlaams opleidingsverlof
