### ISSUE TITLE
TAV personen ondersteunen bij een organisatie

### ISSUE THREAD

**Issue by nicojs** [nicojs/rock-solid#19]
Momenteel is een organisatie 1 niveau met de volgende velden:

naam, terAttentieVan, emailadres, adres, opmerking, doelgroep, telefoonnummer, website, folderVoorkeur, communicatieVoorkeur, soorten, 

Ik wil daar 2 niveaus van maken: een organistatie heeft 1 of meer afdelingen:

Organisatie krijgt dan de volgende velden:
naam

Afdeling krijgt de volgende velden:
naam (maar dan van de afdeling), terAttentieVan, emailadres, adres, adresId, opmerking, doelgroep, telefoonnummer, website, folderVoorkeur, communicatieVoorkeur, soorten,

**Comment by nicojs** [comment]
@SusDK 

Ik ben nog eens door de data gegaan, maar ik kom toch vaak dezelfde afdeling tegen. Bijvoorbeeld "CLB Gemeenschapsonderwijs Halle" 3 keer. Lijkt eerder op 1 afdeling, maar met 3 personen van interesse (TAV).

**Comment by nicojs** [comment]
Misschien is deze onderverdeling beter:

Organisatie:
naam, website, opmerking

Contactpersoon (binnen de organisatie):
terAttentieVan, emailadres, adres, opmerking, doelgroep, telefoonnummer, folderVoorkeur, communicatieVoorkeur

@SusDK laat maar weten wat de voorkeur heeft. Ook of de naam "Contactpersoon" een goede is, want misschien gebruiken jullie die naam al voor andere dingen, dan moeten we een andere naam vinden.

**Comment by SusDK** [comment]
Nico,

Contactpersoon is op zich een belangrijke en een goede omschrijving die wij ook al gebruiken, maar door de vele fusies in de sector gaat afdeling of deelwerking ook een belangrijk criterium zijn.

Sus

Van: Nico Jansen ***@***.***>
Verzonden: vrijdag 15 april 2022 8:53
Aan: nicojs/rock-solid ***@***.***>
CC: Sus Maerschalck ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [nicojs/rock-solid] Afdelingen ondersteunen bij een organisatie (Issue #19)


Misschien is deze onderverdeling beter:

Organisatie:
naam, website, opmerking

Contactpersoon (binnen de organisatie):
terAttentieVan, emailadres, adres, opmerking, doelgroep, telefoonnummer, folderVoorkeur, communicatieVoorkeur

@SusDK<https://github.com/SusDK> laat maar weten wat de voorkeur heeft. Ook of de naam "Contactpersoon" een goede is, want misschien gebruiken jullie die naam al voor andere dingen, dan moeten we een andere naam vinden.

**Comment by nicojs** [comment]
Bedankt @SusDK . We hebben zojuist telefonisch contact gehad. We hebben het volgende besloten:

* Bij een organisatie kun je 0 of meer _TAV_ personen toevoegen
* In het overzicht van "overige personen" komen deze personen dan ook terug, inclusief de naam van de organisatie waar deze persoon toe behoord (maximaal 1 orgnisatie)
* We voegen een extra veld "Afdeling" toe aan een persoon. Deze kan dan ingevuld worden bij het toevoegen bij een organisatie

We hebben het daarnaast gehad over communicatie voorkeur, maar daar maak ik een los issue voor aan.

**Comment by nicojs** [comment]
Ik heb dit toch subtiel anders geïmplementeerd. De TAV personen komen toch _niet_ terug in het overzicht van "overige personen". Dit is zou toch te onlogisch zijn, omdat een TAV contact ook een afdeling bv kan zijn (geen persoon).

Ik heb er daarom voor gekozen om bij een organisatie meerdere TAV contacten toe te staan. Deze hebben wel een foldervoorkeur en afdeling.
