### ISSUE TITLE
[BUG] <titel>Bij DE KEI vormingsuren en begeleidingsuren

### ISSUE THREAD

**Issue by SusDK** [nicojs/rock-solid#224]
### Dit gebeurt er nu

medewerkers vullen vormingsuren in en begeleidingsuren maar in het totaal overzicht van de projecten verandert er niets

### Dit had ik verwacht

Kan je dit even bekijken, het aantal vormingsuren is steeds wijzigend omdat er geregeld in 2 groepen wordt gewerkt. Een weekend is dan niet 19 vormingsuren maar bijvoorbeeld 28 of 29 of 30.

**Comment by nicojs** [comment]
Hoi Sus, volgens mij werkt het zoals ik het bedacht heb.

Momenteel is er voor geen enkele cursus begeleidingsuren geregistreerd. Bv voor de cursus `DK/24/010`: 

https://prd-rock-solid-web.azurewebsites.net/cursussen/2569/edit

Deze moeten dus ingevuld worden en dan update het totaaloverzicht op het homescherm van Rock Solid.

Wat betreft weekenden in 2 groepen: mijn idee daarbij is dat dan gewoon het totaal aantal vormingsuren en begeleidingsuren ingevuld worden bij de cursus. Dan komt het goed terug in alle rapporten en totalen.

Mis ik dan nog iets?
