### ISSUE TITLE
[BUG] Begeleidingsuren zijn altijd minder dan vormingsuren

### ISSUE THREAD

**Issue by nicojs** [nicojs/rock-solid#242]
### URL

https://prd-rock-solid-web.azurewebsites.net/cursussen/2562/edit

### Dit gebeurt er nu

Begeleidingsuren moeten momenteel altijd meer zijn of gelijk zijn aan de vormingsuren.
![image](https://github.com/nicojs/rock-solid/assets/1828233/a2e33279-22c1-4127-92a0-dce526faedbb)

### Dit had ik verwacht

 Deze check moet _juist andersom zijn_, dus begeleidingsuren moeten juist altijd meer zijn dan vormingsuren.

Klopt dit @SusDK

**Comment by SusDK** [comment]
nee deze moeten onafhankelijk kunnen zijn van elkaar: bijvoorbeeld bij cursussen zijn de vormingsuren steeds meer dan de begeleidingsuren. Bij de vakantieprojecten zijn de vormingsuren steeds minder dan de begeleidingsuren.
Een hele dag met overnachting is bij ons 16 uur hiervan kunnen maximaal 10 vormingsuren zijn. Maar deze vormingsuren kunnen toch meer dan 10 zijn wanneer men in 2 groepen werkt.
Dus bijvoorbeeld: een weekend waar normaal maximum 19 vormingsuren zijn, kunnen toch 30 of meer bedragen wanneer men voornamelijk in 2 groepen werkt. Bij de vakanties is dit niet het geval, zijn er soms een beperkt aantal vormingsuren 12 of 20 of 30, maar zijn er meer dan 100 begeleidingsuren, deze worden berekend per vrijwilliger en per dag gerekend. 16 uur - 3 vormingsuren is 13 begeleidingsuren x 2 =26. Ik zet even twee exelfiles erbij hoe we het bereken voor cursussen en voor vakantie
[cursus DK24-030 opvolging gesplitste uren.xlsx](https://github.com/nicojs/rock-solid/files/14883460/cursus.DK24-030.opvolging.gesplitste.uren.xlsx)
[cursus dk-23-2260 Engeland Zuidkust.xlsx](https://github.com/nicojs/rock-solid/files/14883470/cursus.dk-23-2260.Engeland.Zuidkust.xlsx)

**Comment by nicojs** [comment]
Aha duidelijk. Ik fix het en release het straks.

**Comment by nicojs** [comment]
Fix zit in [v1.7.2](https://github.com/nicojs/rock-solid/releases/tag/v1.7.2), wordt nu uitgerold.
