### ISSUE TITLE
[BUG] <titel>aanmaken van een cursus

### ISSUE THREAD

**Issue by SusDK** [nicojs/rock-solid#37]
### URL

https://acc-rock-solid-web-app.azurewebsites.net/cursussen/new/

### Dit gebeurt er nu

Hartje blijft kloppen, maar niets wordt opgeslagen.
Ik heb geprobeerd 2 cursussen aan te maken: DK/23/010 en DK/23/110

**Comment by nicojs** [comment]
Ik heb de bug gevonden. Hij trad op wanneer je de datum/tijd probeerde in te stellen. Dat is nu opgelost.
