### ISSUE TITLE
verwijderen van een persoon bij extra personen

### ISSUE THREAD

**Issue by SusDK** [nicojs/rock-solid#38]
### Idee

Ik kan al nieuwe andere personen toevoegen.
Heb mezelf als exemplarisch voorbeeld genomen. 
Stond als Franciscus al in AV van De Kei. Heb het veranderd in Sus (Franciscus)
Had eerder al een Sus als personeel aangemaakt.
Ik kan deze laatste niet verwijderen blijkbaar.

**Comment by nicojs** [comment]
Gesloten in [6a70747](https://github.com/nicojs/rock-solid/commit/6a70747f11378477f055c52c54eacdc0fa9daf28)
