### ISSUE TITLE
Begeleiders

### ISSUE THREAD

**Issue by elimarte** [nicojs/rock-solid#40]
### Dit gebeurt er nu

In de lijst die verschijnt wanneer je bij een cursus begint te typen, komen ook deelnemers te staan. 

### Dit had ik verwacht

Een lijst die verschijnt waarin je enkel kunt kiezen uit personeel. 
Het zou ook handig zijn als er een 'veetje' staat waarmee je de lijst al kunt open klikken zonder dat je moet beginnen typen.

**Comment by nicojs** [comment]
Deelnemers worden niet getoond, maar wel alle overige personen. Dus ook vrijwilligers. Waarschijnlijk wil je enkel vrijwilligers tonen bij vakanties en begeleiders bij cursussen, correct?

**Comment by nicojs** [comment]
> Deelnemers worden niet getoond, maar wel alle overige personen. Dus ook vrijwilligers. Waarschijnlijk wil je enkel vrijwilligers tonen bij vakanties en begeleiders bij cursussen, correct?

Zo heb ik het nu geïmplementeerd.
