### ISSUE TITLE
Kalender

### ISSUE THREAD

**Issue by elimarte** [nicojs/rock-solid#41]
### URL

https://acc-rock-solid-web-app.azurewebsites.net/cursussen/1/edit/

### Idee

Het zou handig zijn als er de kalender en het klokje vanzelf verschijnt als je de van-tot  bij een cursus wil invullen.

**Comment by nicojs** [comment]
Opgelost met https://github.com/nicojs/rock-solid/commit/6e9f2dab890d24a89bf0037b36b440d14b17539b
