### ISSUE TITLE
Persoon inschrijven

### ISSUE THREAD

**Issue by elimarte** [nicojs/rock-solid#42]
### URL

https://acc-rock-solid-web-app.azurewebsites.net/cursussen/3/inschrijvingen/

### Dit gebeurt er nu

Bij inschrijven van een persoon, is het niet meteen duidelijk dat het de bedoeling is dat je iemands naam moet invullen. Er staat in de grijze tekst enkel 'persoon inschrijven'. 

Ook kwam er meteen bij te staan dat het iemands eerste cursus was. Op basis van wat wordt dat bepaald? Enkel de naam? Dat is misschien niet voldoende, aangezien er wel eens mensen kunnen zijn met dezelfde naam.

**Comment by nicojs** [comment]
> Er staat in de grijze tekst enkel 'persoon inschrijven'.

Welke tekst zou beter zijn? Bv 'naam' of 'Vul hier de naam in'?

**Comment by nicojs** [comment]
> > Er staat in de grijze tekst enkel 'persoon inschrijven'.
> 
> Welke tekst zou beter zijn? Bv 'naam' of 'Vul hier de naam in'?

We hebben het erover gehad en 'Naam persoon' leek ons het beste
