### ISSUE TITLE
[Nieuwe Idee] Woonsituatie

### ISSUE THREAD

**Issue by nicojs** [nicojs/rock-solid#48]
### Idee

Moet nog uitgebreid worden.

@elimarte @SusDK  willen jullie deze hier aanvullen?

**Comment by nicojs** [comment]
Nu is het dit:

- "Ambulante of mobiele woonondersteuning", "Residentiële woonondersteuning", "Thuis/Pleegzorg", "Andere"

Maar we maken ervan:

- Onbekend
- (Pleeg)ouders met professionele begeleiding
- (Pleeg)ouders zonder professionele begeleiding
- Residentiële woonondersteuning
- Zelfstandig met professionele begeleiding
- Zelfstandig zonder professionele begeleiding
- Anders, namelijk:

**Comment by SusDK** [comment]
Akkoord
