### ISSUE TITLE
[Nieuwe Idee]  Aanmeldingen per jaar laten zien op inschrijvingenscherm

### ISSUE THREAD

**Issue by nicojs** [nicojs/rock-solid#63]
### Idee

Aanmeldingen per jaar laten zien op inschrijvingenscherm, zodat makkelijker gekozen kan worden wie op de wachtlijst komt te staan. Hierbij gaat het niet om wachtlijst of annulatie.

**Comment by nicojs** [comment]
Handige shortcut voor nu: navigeren naar persoon mogelijk maken zodat je snel kan zien waar die persoon zich voor ingeschreven heeft. Moet natuurlijk wel de status ook zichtbaar worden daar.

**Comment by SusDK** [comment]
Inderdaad het verschil tussen aanmelden en andere statussen: bevestigd, wachtlijst, geannuleerd ,
