### ISSUE TITLE
[Nieuwe Idee] Prijs bij een cursus

### ISSUE THREAD

**Issue by nicojs** [nicojs/rock-solid#78]
### Idee

In de oude database kun je een prijs bij een cursus registreren. Is dat nog belangrijk @SusDK ?

**Comment by nicojs** [comment]
Hoi @SusDK zou jij hierop willen antwoorden? @elimarte denkt dat dit niet belangrijk is.

**Comment by SusDK** [comment]
Prijzen wel bij op termijn

**Comment by nicojs** [comment]
Ik heb het al ineens geïmplementeerd, want dan kon ik de prijzen van bestaande cursussen ook ineens mee migreren.
